<a href="https://colab.research.google.com/github/OH1107/aisa_edu/blob/master/NLP/20200902_%EB%8B%A8%EC%96%B4%ED%91%9C%ED%98%84%EC%8B%A4%EC%8A%B5_OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# OneHotEncoding 직접 구현

In [ ]:
# 인코딩 대상 단어 리스트
word_ls = ['원숭이','바나나','사과','코끼리']

In [ ]:
from collections import defaultdict
import numpy as np
# {단어 : 인덱스} 사전 구축
word2id_dic = defaultdict(lambda:len(word2id_dic))

for word in word_ls:
    word2id_dic[word]
    
print(word2id_dic)

defaultdict(<function <lambda> at 0x000001F1FCA2A438>, {'원숭이': 0, '바나나': 1, '사과': 2, '코끼리': 3})


In [ ]:
# 고유단어개수: 4개
n_unique_words = len(word2id_dic) # 4값 부여

In [ ]:
# 원핫벡터를 만들기 위해 비어있는 벡터 생성
one_hot_vectors = np.zeros((len(word_ls),n_unique_words)) # 4*4 0값의 벡터 생성

In [ ]:
for i, word in enumerate(word_ls):
    index = word2id_dic[word]
    print(index)
    one_hot_vectors[i,index] += 1
    print(one_hot_vectors)
    print('-'*10)

0
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------
1
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------
2
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
----------
3
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
----------


# sklearn으로 OneHotEncoding구현하기

In [ ]:
# sklearn을 활용한 one-hot encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# 예제 데이터 배열
values = array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [ ]:
# 문자열에 숫자를 붙임
label_enc = LabelEncoder()  # 선언
int_enc = label_enc.fit_transform(values)
int_enc

array([2, 0, 1, 3], dtype=int64)

In [ ]:
# binary encode
onehot_enc = OneHotEncoder(sparse=False) # 선언
int_enc = int_enc.reshape(len(int_enc),1) # n:1 matrix로 변환
onehot_enc = onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])