In [1]:
#Numpy 불러오기 
import numpy as np

#배열 생성하기
arr=np.array([1,2,3,4])
print (arr)
#리스트와 다름 array는 ','가 없음
#array함수를 이용하여 만든 랭크 1(?)의 배열임

[1 2 3 4]


In [2]:
# 3*3배열에 0값 부여
np.zeros((3,3))
# 2*2배열에 1값 부여
np.ones((2,2))
# 4*4배열 초기화되지 않은 값이 들어있는 배열
np.empty((4,4))

#배열에는 문자도 숫자화 되어 처리된다고 함

array([[6.23042070e-307, 7.56587584e-307, 1.37961302e-306,
        1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 1.24611674e-306,
        1.29061821e-306],
       [6.23057349e-307, 1.29062025e-306, 8.34445562e-308,
        2.22507386e-306]])

In [3]:
# arange를 사용하여 배열 만들기 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 2행 3열 배열 생성
arr=np.array([[1,2,3],
              [2,3,4]]) #대괄호 갯수 주의
print(arr)

[[1 2 3]
 [2 3 4]]


In [5]:
#shape으로 배열 모양 확인하기
arr.shape

(2, 3)

In [6]:
#ndim으로 2차원 (차수) 확인하기
arr.ndim

2

In [7]:
#dtype으로 데이터 타입 확인하기
arr.dtype

dtype('int32')

In [8]:
#astype 함수를 사용하여 정수형 데이터 -> 실수형 데이터 배열로 변환

arr_int = np.array([1,2,3,4])
print(arr_int.dtype)
arr_float=arr_int.astype(np.float64) #실수형 데이터로 변환
arr_float.dtype

int32


dtype('float64')

In [9]:
arr_str=np.array(['1','2','3']) #문자형 데이터 배열 생성
print(arr_str.dtype)
arr_int = arr_str.astype(np.int64) #정수형 데이터로 변환
arr_int.dtype

<U1


dtype('int64')

In [10]:
#배열 연산
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

print(arr1+arr2)          #배열끼리의 합 두가지 방법 (각자의 차원에 맞게 연산 함)
print('-'*20)
print(np.add(arr1,arr2))
print('-'*20)
print(arr1*arr2)          #배열끼리의 곱 두가지 방법 (ㅇㅇ 같은 차원끼리)
print('-'*20)
print(np.multiply(arr1,arr2))

[[ 6  8]
 [10 12]]
--------------------
[[ 6  8]
 [10 12]]
--------------------
[[ 5 12]
 [21 32]]
--------------------
[[ 5 12]
 [21 32]]


In [11]:
#dot 함수를 사용하여 행렬의 곱 계산
#계산법은 행렬의 곱ㅜㅜㅜㅜㅜ(arr1의 1행과 arr2의 1열간의 연산 )
print(arr1.dot(arr2))      #배열 객체에 메소드 dot 함수 사용
print('-'*20)
print(np.dot(arr1,arr2))   #Numpy 모듈 함수로 dot 함수 사용

[[19 22]
 [43 50]]
--------------------
[[19 22]
 [43 50]]


In [12]:
#배열 슬라이싱
arr=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
arr_1=arr[:2,1:3]  #[  행:행  ,  열:열]
print(arr_1)

#슬라이스한 배열 원본 배열을 바꾸는 것
#뷰가아닌 새로운 배열 생성할라면 arr[행:행,열:열].copy()로 사본 ㄱ

[[2 3]
 [5 6]]


In [13]:
#배열 인덱싱 (어디자리에 무슨 값있는지)

arr=np.array([[1,2,3]
             ,[4,5,6]
             ,[7,8,9]])
print(arr[0,2])   #0행 2열 값 호출
print(arr[[0,1,2],[2,0,1]])  #0,1,2행의 2,0,1열 값에 접근

#배열 인덱싱은 값만 찾아주는 거임, 원본 배열 수정 안됨

3
[3 4 8]


In [14]:
#Boolean 배열 인덱싱

arr=np.array([[1,2,3],[4,5,6]])
idx=arr>3   #arr에서 3보다 큰 값을 찾아서 같은 모양의 True/False 값을 가진 배열 할당
print(idx)
print('-'*20)
print(arr[idx])   #만들어 놓은 idx배열을 통해 조건에 맞는 배열 구성

#idx값들은 3보다 큰지 작은지만 0,1로 나타내는거임

[[False False False]
 [ True  True  True]]
--------------------
[4 5 6]


In [15]:
# 구글에서 winequality-red.csv 검색
# https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/ 여기 가서
# 레드 화이트 받아서 저장

# 파일 불러오기    

#csv파일 열어보면 데이터가 ';'로 분류되어 있음 그래서 <delimiter=';'> 사용 
#skiprows는 csv 1행은 숫자 데이터가 아니라 범주를 나타냄
#그래서 에러를 막으려고 문자가 들어간 1행 스킵
redwine=np.loadtxt(fname='c:/Ohhhhh/winedata/winequality-red.csv', delimiter=';', skiprows=1, )
whitewine=np.loadtxt(fname='c:/Ohhhhh/winedata/winequality-white.csv', delimiter=';', skiprows=1)

#redwine=np.loadtxt(fname='url주소') 로도 가능

print(redwine)
print('-'*60)
print(whitewine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
------------------------------------------------------------
[[ 7.    0.27  0.36 ...  0.45  8.8   6.  ]
 [ 6.3   0.3   0.34 ...  0.49  9.5   6.  ]
 [ 8.1   0.28  0.4  ...  0.44 10.1   6.  ]
 ...
 [ 6.5   0.24  0.19 ...  0.46  9.4   6.  ]
 [ 5.5   0.29  0.3  ...  0.38 12.8   7.  ]
 [ 6.    0.21  0.38 ...  0.32 11.8   6.  ]]


In [16]:
print(redwine.shape)
print(redwine.ndim)
print(redwine.dtype)

(1599, 12)
2
float64


In [17]:
# 데이터 다루기....
# sum() 전제 데이터들의 합 (별 의미 없)
print(redwine.sum())

152084.78194


In [18]:
# mean() 전체 데이터 평균 (별 의미 없)
print(redwine.mean())
print('-'*60)

# mean(axis=0) 각 열 평균 axis=0 -> x축, row, 행
print(redwine.mean(axis=0))
print('-'*60)

# mean(axis=1) 각 행 평균 
print(redwine.mean(axis=1))
print('-'*60)

# 데이터전체 행, 첫번째 열에 대한 데이터들의 평균
print(redwine[:,0].mean())

7.926036165311652
------------------------------------------------------------
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]
------------------------------------------------------------
[ 6.21198333 10.25456667  8.30825    ...  8.37347833  8.76795583
  7.7077075 ]
------------------------------------------------------------
8.31963727329581


In [19]:
#https://numpy.org/doc/stable/user/quickstart.html








#위의 링크 예시 따라하기

In [20]:
a=np.arange(15).reshape(3,5) #reshape() 뒤에 행열순서로 차수를 늘려나감 (3행 5열로 만들어줘)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
a.shape

(3, 5)

In [22]:
a.ndim

2

In [23]:
a.dtype.name

'int32'

In [24]:
a.itemsize

4

In [25]:
type(a)

numpy.ndarray

In [26]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [27]:
type(b)

numpy.ndarray

In [28]:
a=np.arange(24).reshape(2,3,2,2) #reshape을 이용한 4차원 배열 맨뒤 두개가 행열
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [29]:
a=np.array([2,3,4])
a

array([2, 3, 4])

In [30]:
a.dtype

dtype('int32')

In [31]:
b=np.array([1.2,3.5,5.1])
b

array([1.2, 3.5, 5.1])

In [32]:
a=(1,2,3)
np.array(a)

array([1, 2, 3])

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [35]:
np.empty((2,3))

array([[ 6.21198333, 10.25456667,  8.30825   ],
       [ 8.37347833,  8.76795583,  7.7077075 ]])

In [36]:
np.arange(10,30,5) #시작값, 끝값, 스텝값(몇씩커지는 값)

array([10, 15, 20, 25])

In [37]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [38]:
np.linspace(0,2,9) #시작값, 끝값, 스텝값이 동일하게 n값으로 나눠줘라

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [39]:
x=np.linspace(0,2*np.pi,100) #pi가 3.14---- 원주율 파이
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [40]:
f=np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [41]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [42]:
b=np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [43]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [44]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [45]:
a=np.array([20,30,40,50])
b=np.arange(4) #[0,1,2,3]
c=a-b
c

array([20, 29, 38, 47])

In [46]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [47]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [48]:
print(a<35)
a[a<35]

[ True  True False False]


array([20, 30])

In [49]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A * B 

array([[2, 0],
       [0, 4]])

In [50]:
print(A.dot(B))
print(np.dot(A,B))
print(A@B)

[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [51]:
#뭔지 잘 모르겠음 뭐 난수하나를 뽑는 제너레이터 (함수랑 비슷한 개념인듯)
rg = np.random.default_rng(1)
rg

Generator(PCG64) at 0x1F227C58D60

In [52]:
a=np.ones((2,3), dtype=int)
b=rg.random((2,3))
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [53]:
#컴파일 할 때마다 값이 바뀜
b+=a   #실수에다 정수를 더하는 건 가능, 근데 정수에다가 실수를 더하는건 불가능
b      #그래서 numpy는 걍 다 float로 지정하고 사용

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [54]:
a=np.ones((2,3), dtype=int)
np.random.seed(0)   #seed라는 매소드로 아무 숫자나 지정해주면 랜덤수가 똑같은것만 나오게할수있음
b=np.random.rand(2,3)  #0부터 1사이 균일 분포의 난수 생성
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [55]:
a=rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [56]:
a.sum()

3.1057109529998157

In [57]:
a.min()

0.027559113243068367

In [58]:
a.max()

0.8277025938204418

In [59]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
b.sum(axis=0)  

array([12, 15, 18, 21])

In [61]:
b.min(axis=1)

array([0, 4, 8])

In [62]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [63]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [64]:
a.sum(axis=0)  #1차원끼리의합(같은자리끼리 더함)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [65]:
a.sum(axis=1) #같은 열간의 합

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [66]:
a.sum(axis=2) #같은 행끼리의 합

array([[ 6, 22, 38],
       [54, 70, 86]])

In [67]:
a = np.arange(6).reshape(2,3) + 10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [68]:
#argmax....... 노란박스

#전체 인덱스중에 가장 큰 인자를 알려줌
np.argmax(a)   # 0, 1, 2
               # 3, 4, 5

5

In [69]:
#열 내에서 가장 큰 인자를알려줌 (맨 윗줄부터 0)
np.argmax(a, axis=0)

array([1, 1, 1], dtype=int64)

In [70]:
#행 내에서 가장 큰 인지라르 알려줌 (맨 왼쪽부터 0)
np.argmax(a, axis=1)

array([2, 2], dtype=int64)

In [71]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [72]:
#인덱싱과 슬라이싱

print(a[2])
print(a[2:5])

8
[ 8 27 64]


In [73]:
# 처음 부터 6번째 수까지 2번씩 건너뛰며 1000으로 바꿈
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [74]:
#-1을 넣으면 거꾸로 정렬
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [75]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [76]:
#함수기능을 불러내서 배열 만들기

def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)  ##### x랑 y에 (5,4) 배열이 만들어질때까지 0부터 차례대로 대입됨
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [77]:
b[2,3]

23

In [78]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [79]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

In [80]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [81]:
c = np.array( [[[  0,  1,  2],             
                [ 10, 12, 13]],
                [[100,101,102],
                [110,112,113]]])
c.shape

(2, 2, 3)

In [82]:
c[1,...]   # c[1,:,:] 이랑 똑같음

array([[100, 101, 102],
       [110, 112, 113]])

In [83]:
c[...,2]    #c[:,:,2] 랑 똑같음

array([[  2,  13],
       [102, 113]])

In [84]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [85]:
# .flat 매서드를 쓰면 플랫하게 펴진다고 함 ...

for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [86]:
# .floor 소수점아래를 무조건 무시   .ceil   소수점아래를 올림    .round  얘가 반올림

a = np.floor(10*rg.random((3,4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [87]:
# flat은 열에 맞춰 나열
# ravel은 행에 맞춰 나욜

a.ravel()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [88]:
a.reshape(6,2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [89]:
# .T는 행과 열을 바꾼다 (3,4) 였던 배열 -> (4,3)으로
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [90]:
a = np.floor(10*rg.random((2,2)))
b = np.floor(10*rg.random((2,2)))

print(a)
print(b)

[[9. 7.]
 [5. 2.]]
[[1. 9.]
 [5. 1.]]


In [91]:
# 열에 따라 배열 합치기

np.vstack((a,b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [92]:
# 행에 따라 배열 합치기

np.hstack((a,b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [93]:
#newaxis 나오는데 그냥 참고해도될듯 뭔 소린지 모름 stack 함수로 충분히 됨 패스


In [94]:
a = np.floor(10*rg.random((2,12)))
a

array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])

In [95]:
#열을 따라 세등분 나누기

np.hsplit(a,3)

[array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]]),
 array([[0., 5., 4., 0.],
        [1., 8., 6., 7.]]),
 array([[6., 8., 5., 2.],
        [1., 8., 1., 0.]])]

In [96]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
b=a
b is a

True

In [98]:
c = a.view()
c is a

False

In [99]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
c.base is a

##카피와 뷰를 통해서 원본은 바꾸지 않으면서 핸들링 할 수 있다는 점을 이야기하는 듯

False

In [101]:
c = c.reshape((2, 6))
a.shape

(3, 4)

In [102]:
c[0,4]=1234
a

#근데 이건 또 왜 바뀜?

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [103]:
d = a.copy()
d is a

False

In [104]:
d.base is a

False

In [105]:
d[0,0] = 9999
a

# copy()는 완전 딴판인듯 얜 리턴값 걍 1도 없

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [106]:
palette = np.array([[0, 0, 0],         # black
                     [255, 0, 0],       # red
                     [0, 255, 0],       # green
                     [0, 0, 255],       # blue
                     [255, 255, 255]])  # white
image = np.array([[0,1,2,0],[0,3,4,0]])

palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])